# Generated by Django 4.0 on 2024-01-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_rename_hide_postproject_cacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postjobs',
            old_name='hide',
            new_name='cacher',
        ),
        migrations.RenameField(
            model_name='postjobs',
            old_name='price',
            new_name='prix',
        ),
    ]
