# Generated by Django 5.0.1 on 2024-02-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_rename_hide_postjobs_cacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjobs',
            name='skills_tags_jobs',
        ),
        migrations.RemoveField(
            model_name='tagsprojects',
            name='tags_users_projects',
        ),
        migrations.RemoveField(
            model_name='postproject',
            name='skills_tags_projects',
        ),
        migrations.DeleteModel(
            name='TagsJobs',
        ),
        migrations.DeleteModel(
            name='TagsProjects',
        ),
    ]
