# Generated by Django 5.0.1 on 2024-02-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_education_year_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='links_media',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_tags_user',
        ),
    ]
