# Generated by Django 5.0.1 on 2024-02-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_links_media_and_more'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsuser',
            name='tags_user',
        ),
        migrations.DeleteModel(
            name='Social_media',
        ),
        migrations.DeleteModel(
            name='TagsUser',
        ),
    ]
